"""Seventh migration

Revision ID: 7e1f7d566ae1
Revises: e7ddd8bd34f6
Create Date: 2019-04-22 00:00:59.780814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1f7d566ae1'
down_revision = 'e7ddd8bd34f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('categ', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'categ')
    # ### end Alembic commands ###
