"""Fifth migration

Revision ID: f293121ec9a4
Revises: 2b081cdd6c62
Create Date: 2019-04-21 17:00:01.970161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f293121ec9a4'
down_revision = '2b081cdd6c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('profile', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
